name: Build

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Download and extract Android SDK Command-line Tools
        run: |
          curl -o cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
          mkdir -p $HOME/cmdline-tools
          unzip -q -d $HOME/cmdline-tools cmdline-tools.zip

      - name: Accept Android SDK licenses
        run: $HOME/cmdline-tools/tools/bin/sdkmanager --licenses

      # Utilizza il percorso delle nuove Command-line Tools nei passaggi successivi
      - name: Esegui il tuo passaggio successivo
        run: |
          $HOME/cmdline-tools/tools/bin/sdkmanager --version
          # Aggiungi qui i tuoi comandi successivi che dipendono dalle Android SDK
