name: Build

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Download and extract Android SDK Command-line Tools
        run: |
          curl -o cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
          mkdir -p $RUNNER_TEMP/android-sdk
          unzip -q -d $RUNNER_TEMP/android-sdk cmdline-tools.zip
          mv $RUNNER_TEMP/android-sdk/cmdline-tools $ANDROID_SDK_ROOT
      
      - name: Accept Android SDK licenses
        run: $ANDROID_SDK_ROOT/tools/bin/sdkmanager --licenses

      # Altri passaggi del flusso di lavoro che utilizzano le Android SDK
